Add prod dependency on typing-extensions
Apparently aiosignal requires this without declaring the dependency
properly?

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import mwapi  # type: ignore
    ^^^^^^^^^^^^
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/mwapi/__init__.py", line 15, in <module>
    from .session import Session
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/mwapi/session.py", line 22, in <module>
    from .errors import (APIError, ClientInteractionRequest, ConnectionError,
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/mwapi/errors.py", line 20, in <module>
    import aiohttp
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/aiohttp/client.py", line 107, in <module>
    from .tracing import Trace, TraceConfig
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/aiohttp/tracing.py", line 5, in <module>
    from aiosignal import Signal
  File "/data/project/translate-link/www/python/venv/lib/python3.11/site-packages/aiosignal/__init__.py", line 14, in <module>
    from typing_extensions import TypeVarTuple
ModuleNotFoundError: No module named 'typing_extensions'